version: '3'
    
services:
    flask:
        container_name: flask_swapi
        build: .
        command: bash -c "export FLASK_APP=app.py &&
                          flask run"
        volumes:
            - ./flask:/flask
        # ports:
        #     - "8000:8000"