version: '3'
    
services:
    flask:
        container_name: flask_swapi
        build: .
        volumes:
            - ./flask:/flask
        ports:
            - "5000:5000"
        environment: 
            FLASK_APP: app
            # FLASK_ENV: development 